# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Walden Pond
email: ben@notionparallax.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Walden Pond is a printed zine that is full of the bits of the web that you 
  are actually interested in. One way to think of it is as a Pocket client made 
  of paper.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://waldenpond.press" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: notionparallax
github_username: notionparallax

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

#manifest
short_name: "Walden Pond"
name: "Walden Pond"
default_locale: "en"
start_url: "/?utm_source=homescreen"
manifest_description: "A little break, to read in peace"
background_color: "#FCFCFC"
theme_color: "#1f597a"
display: fullscreen
